stages:
    - build
    - test
    - deploy

image: alpine

build_a:
    stage: build
    script:
        - echo " Build a"

test_a:
    stage: test
    script:
        - echo " test a"

deploy_b:
    stage: deploy
    script:
        - ssh ubuntu@ec2-34-220-156-84.us-west-2.compute.amazonaws.com  "sudo bash /var/www/html/test.sh"
