before_script:
    - 'command -v ssh-agent >/dev/null || (apk --update add openssh-client)'

stages:
    - build
    - test
    - deploy

image: alpine

build_a:
    stage: build
    script:
        - echo " Build a"

test_a:
    stage: test
    script:
        - echo " test a"

deploy_b:
    stage: deploy
    script:
        - echo "Deploying..."
        #- cat $SSH_PRIVATE_KEY
        - ssh -i "$SSH_PRIVATE_KEY" ubuntu@ec2-34-220-156-84.us-west-2.compute.amazonaws.com  "sudo bash /var/www/html/test.sh"
