

stages:
    - build
    - test
    - deploy

image: alpine

build:
    stage: build
    script:
        - echo " Build a"

test:
    stage: test
    script:
        - echo " test a"

deploy:
    stage: deploy

    before_script:
    - 'command -v ssh-agent >/dev/null || (apk --update add openssh-client)'
    - mkdir -p ~/.ssh
    - echo -e “$SSH_PRIVATE_KEY” > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ‘[[ -f /.dockerenv ]] && echo -e “Host *\n\tStrictHostKeyChecking no\n\n” > ~/.ssh/config’

    script:
        - echo "Deploying now..."
        #- cat $SSH_PRIVATE_KEY
        #- chmod 700 iBial.pem
        - ssh ubuntu@ec2-34-220-156-84.us-west-2.compute.amazonaws.com  "sudo bash /var/www/html/test.sh"
