before_script:
    - 'command -v ssh-agent >/dev/null || (apk --update add openssh-client)'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

stages:
    - build
    - test
    - deploy

image: alpine

build_a:
    stage: build
    script:
        - echo " Build a"

test_a:
    stage: test
    script:
        - echo " test a"

deploy_b:
    stage: deploy
    script:
        - echo "private key is
        - echo $SSH_PRIVATE_KEY
        - ssh ubuntu@ec2-34-220-156-84.us-west-2.compute.amazonaws.com  "sudo bash /var/www/html/test.sh"
