before_script:
    - 'command -v ssh-agent >/dev/null || (apk --update add openssh-client)'

stages:
    - build
    - test
    - deploy

image: alpine

build:
    stage: build
    script:
        - echo " Build a"

test:
    stage: test
    script:
        - echo " test a"

deploy:
    stage: deploy
    script:
        - echo "Deploying..."
        #- cat $SSH_PRIVATE_KEY
        - echo $SSH_PRIVATE_KEY | tr -d '\r' > iBial.pem
        - chmod 700 iBial.pem
        - ssh -i "iBial.pem" ubuntu@ec2-34-220-156-84.us-west-2.compute.amazonaws.com  "sudo bash /var/www/html/test.sh"
